#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: $0 <hostname>"
    exit 1
fi
hostname="$1"

ssh "$hostname" mkdir -p .terminfo .vim .re.pl .tmux/plugins/tpm/ .ssh

rsync -avz ~/.oh-my-zsh "$hostname":
rsync -avz ~/.tmux/plugins/tpm "$hostname":.tmux/plugins
scp ~/.rc/.zshrc "$hostname":
rsync -avz ~/.rc/ssh_rc "$hostname":.ssh/rc
rsync -avz ~/.rc/.gitconfig "$hostname":.gitconfig
rsync -avz ~/.rc/.dircolors "$hostname":.dircolors

remote_path=`ssh "$hostname" pwd`

scp ~/.rc/.tmux.conf "$hostname":
cat <<EOF | ssh "$hostname" bash -c "cat >> .tmux.conf"
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
set-environment -g 'SSH_AUTH_SOCK' '$remote_path/.ssh/ssh_auth_sock'
EOF

# rsync -avz /usr/share/terminfo/r/rxvt* "$hostname":.terminfo/r/
# rsync -avz /usr/share/terminfo/s/screen* "$hostname":.terminfo/s/
# rsync -avz ~/.emacs.d/vim/zenburn/colors/ "$hostname":.vim/colors/
# rsync -avz ~/.emacs.d/.vimrc "$hostname":.vimrc
# rsync -avz ~/.emacs.d/repl.rc "$hostname":.re.pl/repl.rc
