#! perl
use 5.14.0;
use Data::Dumper;
use autodie;

sub on_osc_seq {
    my ($term, $op, $args, $resp) = @_;
    if( $op == 0 ) {
        return 1;
    }
    return;
}

sub on_tt_paste {
    my ($term, $octets) = @_;
    $octets =~ s/\[201~/^[[201~/g;
    $term->tt_paste($octets);
    return 1;
}
